apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: leakplantingregistry.azurecr.io/react-app:new
          ports:
            - containerPort: 3000  # Toegevoegd
          resources:
            requests:
              cpu: "25m"
              memory: "128Mi"
            limits:
              cpu: "50m"
              memory: "256Mi"
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: ClusterIP
  selector:
    app: react-app  # Aangepast om overeen te komen met de Deployment labels
  ports:
    - name: react-app
      protocol: TCP
      port: 80
      targetPort: 3000  # Aangepast om overeen te komen met de containerPort
