apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  namespace: leakplanting
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - 20-238-135-171.nip.io
      secretName: react-app-tls
  rules:
    - host: 20-238-135-171.nip.io
      http:
        paths:
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: cm-acme-http-solver-s7zjz  # Vervang dit door jouw solver service naam
                port:
                  number: 80
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: react-app
                port:
                  number: 443