apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  namespace: leakplanting
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: "20-238-135-171.nip.io"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: react-app-service
            port:
              number: 80
  tls:
  - hosts:
    - "20-238-135-171.nip.io"
    secretName: react-app-tls