name: Push check yml files

on: push

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in kubernetes folder
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: kubernetes
          strict: true
          ignore_missing_schemas: true
          token: ${{ secrets.GITHUB_TOKEN }}
