name: Lint Manifests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint k8s manifest files
        uses: azure/k8s-lint@v3
        with:
          manifests: |
            kubernetes/deployment.yml
            kubernetes/service.yml
            kubernetes/ingress.yml
            kubernets/cluster-issuer.yml
          kubeconformOpts: -summary
